update ci workflow (changelog ignore)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -35,13 +35,13 @@ jobs:
     needs: test_lint
     strategy:
       matrix:
-        node: [ '14', '13', '12' ]
+        node: [ '15', '14', '13', '12' ]
         os: [ windows-latest, ubuntu-latest ]
     name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
     steps:
     - name: Tell if project is using npm or yarn
       id: step1
-      uses: garronej/github_actions_toolkit@v2.2
+      uses: garronej/github_actions_toolkit@v2.4
       with: 
         action_name: tell_if_project_uses_npm_or_yarn
     - uses: actions/checkout@v2.3.4
@@ -95,7 +95,7 @@ jobs:
       to_version: ${{ steps.step1.outputs.to_version }}
       is_upgraded_version: ${{steps.step1.outputs.is_upgraded_version }}
     steps:
-    - uses: garronej/github_actions_toolkit@v2.2
+    - uses: garronej/github_actions_toolkit@v2.4
       id: step1
       with: 
         action_name: is_package_json_version_upgraded
@@ -105,11 +105,10 @@ jobs:
     needs: check_if_version_upgraded
     if: needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true'
     steps:
-    - uses: garronej/github_actions_toolkit@v2.2
+    - uses: garronej/github_actions_toolkit@v2.4
       with:
         action_name: update_changelog
         branch: ${{ github.ref }}
-        commit_author_email: ts_ci@github.com
 
   create_github_release:
     runs-on: ubuntu-latest
@@ -185,3 +184,78 @@ jobs:
       env:
         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
         VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
+
+  publish:
+    runs-on: ubuntu-latest
+    needs: 
+      - update_changelog
+      - check_if_version_upgraded
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+        ref: ${{ github.ref }}
+    - run: rm -r .github
+    - continue-on-error: true
+      run: |
+        git branch -d latest || true
+        git push origin :latest
+        git branch latest
+        git checkout latest
+    - uses: actions/setup-node@v2.1.3
+      with:
+        node-version: '15'
+    - run: |
+        if [ -f "./yarn.lock" ]; then
+            yarn install --frozen-lockfile                                                                                                                                                                                        
+        else
+            npm ci
+        fi
+    - run: npx -y -p denoify@0.6.5 denoify_enable_short_npm_import_path
+      env:
+        DRY_RUN: "0"
+    - name: Publishing on NPM
+      run: |
+        if [ "$(npm show . version)" = "$VERSION" ]; then
+          echo "This version is already published"
+          exit 0
+        fi
+        if [ "$NODE_AUTH_TOKEN" = "" ]; then
+          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
+          false
+        fi
+        npm publish
+      env:
+        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
+        VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
+    - run: |
+        git config --local user.email "actions@github.com"
+        git add -A
+        git commit -am "Enabling shorter import paths"
+        git push origin latest
+    - name: Build GitHub release body
+      id: step1
+      run: |
+        if [ "$FROM_VERSION" = "0.0.0" ]; then
+            echo "::set-output name=body::🚀"
+        else
+            echo "::set-output name=body::📋 [CHANGELOG](https://github.com/$GITHUB_REPOSITORY/blob/v$TO_VERSION/CHANGELOG.md)"
+        fi
+      env: 
+        FROM_VERSION: ${{ needs.check_if_version_upgraded.outputs.from_version }}
+        TO_VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
+    - uses: garronej/github_actions_toolkit@v2.4
+      with:
+        action_name: setup_repo_webhook_for_deno_land_publishing
+        should_webhook_be_enabled: false
+    - uses: garronej/action-gh-release@v0.2.0
+      with:
+        name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
+        tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
+        target_commitish: latest
+        body: ${{ steps.step1.outputs.body }}
+        draft: false
+        prerelease: false
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+
